different text for different type of users
8by8-org/web-app pull request #124
Opened 2022-05-04 02:37 UTC by projectr495836

On the side bar, when user is not challenger, it will show "take the challenge". When user is a challenger, it will show "my challenge".

## Overview 
> REQUIRED
> Fill in the overview of this PR, what this PR is trying to achieve

## Test Plan 
> REQUIRED 
> What you did to verify your PR works as claimed? You should list things/steps/screenshots/screentcasts so that others could reproduce your test easily

## Follow ups 
> It is okay for the PR to be not perfect, list what you/other should work on after this PR is merged

2022-05-05 04:49 UTC, Devanshusp requested changes
Hey @projectr495836, nice work updating the sidebar!

I think we can go ahead and fill out the links for each page; the notifications link has also been removed from the most recent design.
Also, lets see if we can follow the finalized design on #23

2022-05-05 04:49 UTC, Devanshusp commented on src/components/Header/Header.js
> +        path: "/",
All of these lead to the homepage "/" (placeholders from before)
I think we have most of the pages built out now and can start filling it out, ex. "My Challenge" is /progress

2022-05-07 01:57 UTC, wcouturiaux commented
@projectr495836 is this PR for issue #117?

2022-05-16 22:45 UTC, Devanshusp commented
> @projectr495836 is this PR for issue #117?

Yeah

2022-06-08 01:23 UTC, closed without merging