Fix console errors for Issue126
8by8-org/web-app pull request #127
Opened 2022-05-06 04:24 UTC by wcouturiaux

## Overview 
> The following were done to fix console errors on the voter registration page.
1. Change class to className in loadingwheel.js
2. Change conditional className assignment of `<form>` in voterregistrationform.js
3. Replace state hook `loading` and use state hook `page` to remove redundancy of states.

>The following were done to fix an additional console error:
1. Change logo192.png and logo512.png to iconXXX.png in manifest to match image file names in public folder.

## Test Plan 
> 1. After making changes verified loading wheel still shows when `page` state is "loading" and transitions to show `<form>` once loaded.
2. Verify className of `<form>` is changing with the state of `page`
3.  Followed voter registration process to ensure nothing broke.

## Follow-ups 
> Remove state hook `loading` in future (currently commented out)

2022-06-06 03:32 UTC, wcouturiaux commented
@dvorakjt Can you please review?

2022-06-07 02:13 UTC, Devanshusp requested changes
Hey @wcouturiaux, so sorry for not checking this earlier, didn't know it was an active pr 😓

Thanks for working on removing the console errors! I think the updates for the VoterRegistrationForm need to be updated because of merge conflicts (reorganization); everything else looks great!

2022-06-08 04:45 UTC, wcouturiaux commented
@Devanshusp I have to have a look at this tomorrow, I'm not sure if they even apply with the latest changes from @dvorakjt (can you also look at and comment on this might save me a lot of time) Seems like the loading wheel is gone for that page now?

2022-06-22 03:39 UTC, wcouturiaux commented
Updates merged before this made this PR no longer relevant.

2022-06-22 03:39 UTC, closed without merging