Update /actions page #75 (Finish): Added in share.
8by8-org/web-app pull request #130
Opened 2022-05-19 16:37 UTC by MazharulIslam-Naim

## Overview 
This pr adds sharing about actions taken by the player on their social media accounts. It mainly focuses on getting the preview for both invite and share to work. 

## Test Plan 
This was tested manually on Desktop and iPhone.

## Follow ups 
The playerwelcome page in preview might not exactly look how the page looks regularly, so let me know if that needs tweaking.

2022-05-19 22:28 UTC, Devanshusp requested changes
Hey Naim, thanks for working on this pr!

This is so cool! I thought the preview was just supposed to be an image, this is much more robust. One nit through, I would like to see the preview in one page without the first scroll bar.  Feel free to adjust the size of the phone preview.
![image](https://user-images.githubusercontent.com/66650721/169414376-5b9642d1-ba66-4b05-82e3-c3c2b36e1b96.png)

Also, if we could relatively decrease the size of the page (fonts, buttons, icons), I think it would look even better. Something like the figma:
![image](https://user-images.githubusercontent.com/66650721/169414632-dbdbc482-8767-4799-849e-52c2a6f8a914.png)

2022-05-25 02:10 UTC, MazharulIslam-Naim commented
Just leave this styling issue for beta. I have noted it down and I'll fix it later.

2022-05-25 04:15 UTC, githubxxcc commented
Hey Naim, I think there are 2 issues I encountered locally that need to be fixed before merging this

1. It is throwing errors when the players get the link
Steps to reproduce:
- Create a challenger, share the link 
- Open an Incognito window, click on the link 
- While it was being loaded on `/actions` page, it crashed with the below: 
![image](https://user-images.githubusercontent.com/11676094/170178356-15d7ba49-93a7-4964-8175-e948849c7a3c.png)

I believe the issue is there is no `currentUser` logged in yet, so we could not `getUserDatabase()` here in `Invite.js` 


2. Looks like changing the feedback from `<a>` tag to `<button>` creates some styling issue: 
![image](https://user-images.githubusercontent.com/11676094/170178524-85632294-6cb6-4658-838d-e337e55fd7e0.png)

Does it show up on your end?

2022-05-25 05:43 UTC, githubxxcc commented on src/components/Footer.js
> +  // If isShare is not true then the social media buttons work.
Why does `isShare` related to the buttons here?

2022-05-25 05:44 UTC, githubxxcc commented on src/components/Footer.js
> +  // If isShare is not true then the social media buttons work.
oh, coz of the sharing preview... hmm I see.

2022-05-25 06:01 UTC, githubxxcc approved these changes
This is actually a rather complex PR, so well done @MazharulIslam-Naim for putting this up in the first place. 

I am not too sure about the additional `isShare` check everyone to get the `preview` thing working is really worthwhile though. Didn't know we have to do it in such a hacky way, or I would have asked the design team to change the preview to just a static image or even get rid of this requirement. 

But it seems to be working - I tested the local share with both players and challengers, and the non-share views. So why not then, I don't want this little magic get wasted... And anyway,  there is documentation to explain why the `isShare`.

2022-05-25 06:01 UTC, githubxxcc approved these changes

2022-05-25 06:02 UTC, merged