Organize Folders, issue #116
8by8-org/web-app pull request #144
Opened 2022-06-07 03:29 UTC by arniber21

## Overview 
> REQUIRED
> Fill in the overview of this PR, what this PR is trying to achieve
Fixes error #116 with the folder structures

## Test Plan 
> REQUIRED 
> What you did to verify your PR works as claimed? Make sure to list **things/steps/screenshots/screentcasts** so that others could reproduce your test easily. Share styling changes and component updates through screenshots

Went through the webpage before, through the challenger page and through the basic workflow. After going through and organizing folders, everything worked as usual. 

## Follow ups 
> It is okay for the PR to be not perfect, list what you/other should work on after this PR is merged
I made a folder called "utility" to contain straggling components that didn't fit into their own directory. I also left the App.js and App.scss by itself w/o a folder as that is common practice across React.

2022-07-05 23:53 UTC, Devanshusp requested changes, later dismissed
Hey @arniber21, thanks for making so many organizational changes, it was definitely due.

I like how you separated the folders; the only changes I would make are moving the `VoterRegistration` folder and the `ElectionReminders` folder inside the `Actions` folder. Also, the `Notification` folder inside the `Utility` folder. However, this is not required, it still makes sense the way you have it organized.

Otherwise, everything else looks great! There are a few merge conflicts, I'll merge once those are cleared.

2022-07-11 05:11 UTC, arniber21 commented
Should be all fixed now, let me know if you get any errors. It was smooth sailing for me at my end

2022-07-17 01:50 UTC, arniber21 commented
Had to fix a merge conflict real quick - should be good now

2022-07-21 00:42 UTC, arniber21 commented
Fixed merge issues

2022-07-21 01:02 UTC, Devanshusp requested changes
Hey Arnab, the folder organization looks great, just some merge conflicts (something weird is going on with the git).

I'll merge once those are fixed!

2022-07-21 01:02 UTC, Devanshusp commented on src/components/Actions/Actions.js
> +>>>>>>> 0ae281d19ec71fc1ea157a19c9ae493d20e1c524
This looks like git version management
Its preventing some of the files to run

2022-07-21 01:02 UTC, arniber21 commented on src/components/Actions/Actions.js
> +>>>>>>> 0ae281d19ec71fc1ea157a19c9ae493d20e1c524
Huh thats weird, lemme fix that rq

2022-07-21 01:36 UTC, arniber21 commented
I went through and fixed the git errors, site works for me. Although I would check on your end.

2022-07-21 05:34 UTC, Devanshusp approved these changes
Thanks @arniber21! Merging now

2022-07-21 05:34 UTC, merged