change margin of Election Alerts page
8by8-org/web-app pull request #145
Opened 2022-06-11 02:57 UTC by zjiao19

## Overview 
35. Get Election Alerts form: Increase margins to 30px. 

## Test Plan 
Go to /election-reminders and inspect elements to make sure they align correctly.

## Follow ups 
> It is okay for the PR to be not perfect, list what you/other should work on after this PR is merged

2022-06-13 01:31 UTC, MazharulIslam-Naim commented
Hey @zjiao19 thanks for working on this.

The left side seems to be correct but the right side is still a little to close and the top message seems to be overflowing its container. I saw that your adding margins to individual components instead you should remove the left and right padding and margins and just add the margin to the bigger container. 

Let me know if you need help.
![image](https://user-images.githubusercontent.com/27384622/173263957-f4492e0a-b794-4658-b501-16a424ebd76d.png)

2022-06-17 01:41 UTC, zjiao19 commented
Thank you! I fixed the right side margin and move the margin to the bigger container. Please let me know if there's anything else.

2022-06-18 19:20 UTC, MazharulIslam-Naim requested changes

2022-06-18 19:20 UTC, MazharulIslam-Naim commented on src/components/ElectionReminders/ElectionReminder.scss
>      color: black;
Can you the margin-left here to `margin: 0px 30px;`

2022-06-18 19:35 UTC, zjiao19 commented on src/components/ElectionReminders/ElectionReminder.scss
>      color: black;
Sure!

2022-06-19 21:00 UTC, MazharulIslam-Naim approved these changes
@zjiao19 Great work!

2022-06-19 21:01 UTC, merged