[P1-40] Erlocate error messages
8by8-org/web-app pull request #150
Opened 2022-06-28 19:12 UTC by CaptainExtremis

## Overview 
> REQUIRED
> Changed code so that error messages will appear below the corresponding field if filled out incorrectly.

## Test Plan 
> REQUIRED 
> Tested manually by signing out of the app.

## Follow ups 
> N/A

2022-07-02 17:00 UTC, Devanshusp requested changes
Hey @CaptainExtremis, thanks for working on this!
For some reason, I am not able to type in the zip code field anymore-maybe something to do with the onChange event in the zip code input field.

Also, just for future reference, could you please add some screenshots of the changes you made? Helps a ton when checking prs!

2022-07-16 16:49 UTC, Devanshusp requested changes

2022-07-16 16:49 UTC, Devanshusp commented on src/components/VoterRegistration/pages/Eligibility/Eligibility.component.js
> +            return;
After removing this return, the zip code input works as expected.

2022-07-23 17:34 UTC, CaptainExtremis commented
I've tried updating Instagram.js and Eligibility.component.js. See if you can merge them now.

2022-07-25 04:56 UTC, Devanshusp commented
Hmm, still no luck; let me see what I can do

2022-07-25 15:08 UTC, closed without merging