Next js migration
8by8-org/web-app pull request #205
Opened 2023-05-02 10:01 UTC by dvorakjt

## Overview 

This PR achieves the following:

-Set up a Next.js project and folder structure
-Install Inversify and reflect-metadata
-Install sass
-Install jest, react testing framework, etc
-Restructure styles folder and refactor code for DRYness and consistency
-Restructure styles code to follow atomic css principles
-Port and refactor Home page
-Add tests for Home page and PageContainer
-Add github actions file to automate tests upon pull requests
-Add a README.md describing the goals of this initiative 

## Test Plan 
-Jest tests were written for all components and pages included in this PR
-100% code-coverage has been achieved
-Tests are automated upon push and pr for this branch

2023-05-04 01:31 UTC, ty730 requested changes
PR looks really great! Everything is very polished and structured in a logical way which will make things a lot easier in the future. The scss clean up is huge, makes styling much clearer! One small thing, I'm thinking we might want to add .env to the .gitignore.

2023-05-04 01:31 UTC, ty730 commented on .gitignore
Could you add .env or .env* to the .gitignore. I'm worried someone will create a .env without the .local and then it won't get picked up.

2023-05-05 07:18 UTC, dvorakjt commented on .gitignore
Great catch. Done!

2023-05-05 12:34 UTC, ty730 approved these changes

2023-05-05 12:35 UTC, merged